name: Update Top GitHub Users List
on:
  schedule:
    - cron: '0 0 * * *'  # daily
  workflow_dispatch:

jobs:
  update-users:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Update Top Users
        uses: Zaid-maker/top-github-users-action@v1.1.0  # Updated version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          CUSTOM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
